# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVgIRFB7bsS8FDhRcrjY-TAAhP5rV8qP
"""

from sqlalchemy import create_engine
import pandas as pd
import streamlit as st

# -------------------------
# Database Connection
# -------------------------
USER = "postgres"
PASSWORD = "2322"   # 🔑 replace with the password you set in pgAdmin/psql
HOST = "localhost"
PORT = "5432"
DBNAME = "food_wastage"

# SQLAlchemy connection string
DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"

try:
    engine = create_engine(DATABASE_URL)
    conn = engine.connect()
    st.success("✅ Connected to PostgreSQL successfully!")
except Exception as e:
    st.error(f"❌ Connection failed: {e}")

